---
os: linux
dist: xenial
language: node_js
node_js: 11
cache:
  npm: true
  directories:
    - ~/.cache
addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4
services:
  - xvfb
script:
  - npx run-p lint spellcheck test
after_success:
  - npx codecov
deploy:
  provider: script
  edge: true
  script: npx semantic-release
  on:
    branch: master
