---
language: node_js
node_js: node
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - npm run lint
  - npm run spellcheck
  - npm run test
after_success:
  - npx codecov
before_deploy:
  - npm run build
deploy:
  provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    branch: master
