---
language: node_js
node_js: node
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - npm run lint
  - npm run spellcheck
  - npm run test
  - npm run build
deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  repo: kvadevack/kvadevack.github.io
  target-branch: master
  fqdn: kvadevack.se
  on:
    branch: master
