---
language: node_js
node_js: node
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - npx run-p lint spellcheck test
after_success:
  - npx codecov
deploy:
  provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    branch: master
