---
name: CI
on:
- push
- pull_request
jobs:
  ci:
    name: CI
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Setup cache
      uses: actions/cache@v3.0.2
      with:
        path: |
          ~/.npm
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Setup Node.js
      uses: actions/setup-node@v2.5.0
      with:
        node-version: 16.13.1
    - name: Install dependencies
      run: npm ci
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    - name: Run checks
      run: xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" npx run-p lint spellcheck test
      env:
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    - name: Upload coverage report
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
